version: "3.1"

networks:
  frontend:
  backend:

services:
  prometheus:
    image: prom/prometheus:v2.17.1
    user: root
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus_data/:/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=1y'
    ports:
      - 9090:9090
    links:
      - gh_metrics_verb:gh_metrics_verb
      - gh_metrics_adv:gh_metrics_adv
      - gh_metrics_base:gh_metrics_base
      - jira_metrics:jira_metrics
    networks:
      - backend

  grafana:
    image: grafana/grafana:6.7.2
    user: root
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
    networks:
      - backend
      - frontend
 
  gh_metrics_verb:
    image: rostasvo/gh-exporter:1.0.0.Final
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - GH_REPOS=quarkusio/quarkus
      - GH_DETAILS_LEVEL=VERBOSE
      - GH_TOKEN=__TOKEN_1_TODO__
    networks:
      - backend

  gh_metrics_adv:
    image: rostasvo/gh-exporter:1.0.0.Final
    expose:
      - 8080
    ports:
      - 8180:8080
    environment:
      - GH_REPOS=quarkusio/quarkus-quickstarts,quarkusio/quarkusio.github.io,quarkusio/code.quarkus.io,quarkusio/quarkus-platform
      - GH_DETAILS_LEVEL=ADVANCED
      - GH_TOKEN=__TOKEN_2_TODO__
    networks:
      - backend

  gh_metrics_base:
    image: rostasvo/gh-exporter:1.0.0.Final
    expose:
      - 8080
    ports:
      - 8280:8080
    environment:
      - GH_REPOS=quarkusio/quarkus-http,quarkusio/quarkus-workshops,quarkusio/quarkus-images,quarkusio/quarkus-security,quarkusio/quarkus-grpc
      - GH_DETAILS_LEVEL=BASE
      - GH_TOKEN=__TOKEN_2_TODO__
    networks:
      - backend

  jira_metrics:
    image: rostasvo/jira-exporter:1.0.0.Final
    expose:
      - 8080
    ports:
      - 8380:8080
    environment:
      - JIRA_PROJECTS=QUARKUS
      - JIRA_AUTH_USERNAME=__USERNAME_TODO__
      - JIRA_AUTH_PASSWORD=__PASSWORD_TODO__
    networks:
      - backend
