version: "3.1"

networks:
  frontend:
  backend2:

services:
  prometheus:
    image: prom/prometheus:v2.31.1
    user: root
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus_data/:/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=3y'
    ports:
      - 9090:9090
    links:
      - gh_metrics_verb:gh_metrics_verb
      - gh_metrics_adv:gh_metrics_adv
      - gh_metrics_base:gh_metrics_base
      - gh_metrics_cust:gh_metrics_cust
      - jira_metrics:jira_metrics
    networks:
      - backend2

  grafana:
    image: grafana/grafana:8.2.5
    user: root
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
    networks:
      - backend2
      - frontend
 
  gh_metrics_verb:
    image: rostasvo/gh-exporter:1.1.28.Final
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - GH_REPOS=quarkusio/quarkus
      - GH_DETAILS_LEVEL=VERBOSE
      - GH_TOKEN=__TOKEN_1_TODO__
    networks:
      - backend2

  gh_metrics_adv:
    image: rostasvo/gh-exporter:1.1.28.Final
    expose:
      - 8080
    ports:
      - 8180:8080
    environment:
      - GH_REPOS=quarkusio/quarkus-quickstarts,quarkusio/quarkusio.github.io,quarkusio/code.quarkus.io,quarkusio/quarkus-platform
      - GH_DETAILS_LEVEL=ADVANCED
      - GH_TOKEN=__TOKEN_2_TODO__
    networks:
      - backend2

  gh_metrics_base:
    image: rostasvo/gh-exporter:1.1.28.Final
    expose:
      - 8080
    ports:
      - 8280:8080
    environment:
      - GH_REPOS=quarkusio/quarkus-http,quarkusio/quarkus-workshops,quarkusio/quarkus-images,quarkusio/quarkus-security
      - GH_DETAILS_LEVEL=BASE
      - GH_TOKEN=__TOKEN_2_TODO__
    networks:
      - backend2

  gh_metrics_cust:
    image: rostasvo/gh-exporter:1.1.28.Final
    expose:
      - 8080
    ports:
      - 8480:8080
    environment:
      - GH_REPOS=quarkusio/quarkus
      - GH_DETAILS_LEVEL=CUSTOM
      - GH_TOKEN=__TOKEN_1_TODO__
      - GH_OPEN_ISSUES=label:priority/blocker
      - GH_CLOSED_ISSUES=label:priority/blocker,label:kind/bug+-label:triage/invalid+-label:triage/duplicate,label:kind/enhancement+-label:triage/invalid+-label:triage/duplicate
    networks:
      - backend2

  jira_metrics:
    image: rostasvo/jira-exporter:1.1.16.Final
    expose:
      - 8080
    ports:
      - 8380:8080
    environment:
      - JIRA_PROJECTS=QUARKUS
      - JIRA_AUTH_TOKEN=__TOKEN_TODO__
    networks:
      - backend2
