{
 "title": "Quarkus - Overview",
 "description": "A docker stack to collect GitHub statistics",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Quarkus Stars",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gh_repo_stars{repo=\"quarkusio/quarkus\"}",
     "legendFormat": "{{stars}}"
    }
   ]
  },
  {
   "title": "Quarkus Open Issues",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gh_repo_open_issues{repo=\"quarkusio/quarkus\",label!~\"kind.*\"}",
     "legendFormat": "{{Open Issues}}"
    }
   ]
  },
  {
   "title": "Quarkus Forks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gh_repo_forks{repo=\"quarkusio/quarkus\"}",
     "legendFormat": "{{Forks}}"
    }
   ]
  },
  {
   "title": "Quarkus Quickstarts Stars",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gh_repo_stars{repo=\"quarkusio/quarkus-quickstarts\"}",
     "legendFormat": "{{stars}}"
    }
   ]
  },
  {
   "title": "Quarkus Quickstarts Open Issues",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gh_repo_open_issues{repo=\"quarkusio/quarkus-quickstarts\"}",
     "legendFormat": "{{Open Issues}}"
    }
   ]
  },
  {
   "title": "Quarkus Quickstarts Forks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gh_repo_forks{repo=\"quarkusio/quarkus-quickstarts\"}",
     "legendFormat": "{{Forks}}"
    }
   ]
  },
  {
   "title": "Quarkus Site Stars",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gh_repo_stars{repo=\"quarkusio/quarkusio.github.io\"}",
     "legendFormat": "{{stars}}"
    }
   ]
  },
  {
   "title": "Quarkus Site Open Issues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gh_repo_open_issues{repo=\"quarkusio/quarkusio.github.io\"}",
     "legendFormat": "{{Open Issues}}"
    }
   ]
  },
  {
   "title": "Quarkus Site Forks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gh_repo_forks{repo=\"quarkusio/quarkusio.github.io\"}",
     "legendFormat": "{{Forks}}"
    }
   ]
  },
  {
   "title": "Repo size (kB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gh_repo_size{repo=\"quarkusio/quarkusio.github.io\"}",
     "legendFormat": "{{quarkusio.github.io}}"
    },
    {
     "expr": "gh_repo_size{repo=\"quarkusio/quarkus\"}",
     "legendFormat": "{{quarkus}}"
    },
    {
     "expr": "gh_repo_size{repo=\"quarkusio/quarkus-quickstarts\"}",
     "legendFormat": "{{quarkus-quickstarts}}"
    }
   ]
  },
  {
   "title": "Repo watchers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gh_repo_subscribers{repo=\"quarkusio/quarkusio.github.io\"}",
     "legendFormat": "{{quarkusio.github.io}}"
    },
    {
     "expr": "gh_repo_subscribers{repo=\"quarkusio/quarkus\"}",
     "legendFormat": "{{quarkus}}"
    },
    {
     "expr": "gh_repo_subscribers{repo=\"quarkusio/quarkus-quickstarts\"}",
     "legendFormat": "{{quarkus-quickstarts}}"
    }
   ]
  }
 ]
}