{
 "title": "Quarkus - Quarkus.io and code.quarkus.io",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Open Issues",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gh_repo_open_issues{repo=\"quarkusio/quarkusio.github.io\"} or gh_repo_open_issues{repo=\"quarkusio/code.quarkus.io\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Closed Issues",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gh_repo_closed_issues{repo=\"quarkusio/quarkusio.github.io\"} or gh_repo_closed_issues{repo=\"quarkusio/code.quarkus.io\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Open PRs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gh_repo_open_prs{repo=\"quarkusio/quarkusio.github.io\"} or gh_repo_open_prs{repo=\"quarkusio/code.quarkus.io\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Closed / Merged PRs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gh_repo_closed_prs{repo=\"quarkusio/quarkusio.github.io\"} or gh_repo_closed_prs{repo=\"quarkusio/code.quarkus.io\"}",
     "legendFormat": "Closed {{repo}}"
    },
    {
     "expr": "gh_repo_merged_prs{repo=\"quarkusio/quarkusio.github.io\"} or gh_repo_merged_prs{repo=\"quarkusio/code.quarkus.io\"}",
     "legendFormat": "Merged {{repo}}"
    }
   ]
  },
  {
   "title": "Commits",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "gh_repo_commits{repo=\"quarkusio/quarkusio.github.io\"} or gh_repo_commits{repo=\"quarkusio/code.quarkus.io\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Contributors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "gh_repo_contributors{repo=\"quarkusio/quarkusio.github.io\"} or gh_repo_contributors{repo=\"quarkusio/code.quarkus.io\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Tags",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "gh_repo_tags{repo=\"quarkusio/quarkusio.github.io\"} or gh_repo_tags{repo=\"quarkusio/code.quarkus.io\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Forks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "gh_repo_forks{repo=\"quarkusio/quarkusio.github.io\"} or gh_repo_forks{repo=\"quarkusio/code.quarkus.io\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Stars",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "gh_repo_stars{repo=\"quarkusio/quarkusio.github.io\"} or gh_repo_stars{repo=\"quarkusio/code.quarkus.io\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Subscribers / Watchers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "gh_repo_subscribers{repo=\"quarkusio/quarkusio.github.io\"} or gh_repo_subscribers{repo=\"quarkusio/code.quarkus.io\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Size (kB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "gh_repo_size{repo=\"quarkusio/quarkusio.github.io\"} or gh_repo_size{repo=\"quarkusio/code.quarkus.io\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  }
 ]
}