{
 "title": "Quarkus - Base details level repos",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Open Issues and PRs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gh_repo_open_issues_and_prs{job=\"gh_metrics_base\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Stars",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gh_repo_stars{job=\"gh_metrics_base\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Forks",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gh_repo_forks{job=\"gh_metrics_base\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Subscribers / Watchers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gh_repo_subscribers{job=\"gh_metrics_base\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Size (kB)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gh_repo_size{job=\"gh_metrics_base\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  }
 ]
}