{
 "title": "Release Readiness Criteria",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Open Blocker and Critical Issues",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jira_open_blocker", "legendFormat": "{{repo}} - Blocker issues" },
    { "expr": "jira_open_critical", "legendFormat": "{{repo}} - Critical issues" }
   ]
  },
  {
   "title": "Verified Blocker and Critical Issues",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jira_verified_blocker", "legendFormat": "{{repo}} - Blocker issues" },
    { "expr": "jira_verified_critical", "legendFormat": "{{repo}} - Critical issues" }
   ]
  },
  {
   "title": "Open Regression Issues",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jira_open_regression", "legendFormat": "{{repo}} - Regressions" },
    {
     "expr": "jira_open_regression_performance",
     "legendFormat": "{{repo}} - Regressions - Perf"
    },
    { "expr": "jira_open_regression_ha", "legendFormat": "{{repo}} - Regressions - HA" }
   ]
  },
  {
   "title": "Documentation and Untriaged Issues",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jira_open_documentation", "legendFormat": "{{repo}} - Documentation" },
    { "expr": "jira_open_untriaged", "legendFormat": "{{repo}} - Untriaged" }
   ]
  }
 ]
}